### ISSUE TITLE
Changing container layout

### ISSUE THREAD

**Issue by bolt12** [nwg-piotr/autotiling#9] opened 2020-04-25 10:10 UTC
When I enabled autotiling I no longer was able to change the container layout.. is there any way to fix this?

See for reference: https://i3wm.org/docs/userguide.html#_changing_the_container_layout

**Comment by nwg-piotr** [comment] 2020-04-25 13:07
The script has already selected a layout: either `splith` or `splitv`. See [42-44](https://github.com/nwg-piotr/autotiling/blob/5370c92d4b86e327210337abe2fdbdc95957b92d/autotiling.py#L42). So it's a feature, not a bug.

**Comment by bolt12** [comment] 2020-04-25 13:14
So I'm only able to work with splitv/h containers? I wish the script would be aware of this and only select the corresponding splitv/h whenever it was in one of those states

**Comment by nwg-piotr** [comment] 2020-04-25 13:19
Well, I change to tabbed layout with a key binding with no problem, but I'm on sway. I'm not sure what it looks like on i3. Will check later tonight.

**Comment by bolt12** [comment] 2020-04-25 13:20
Okay, thank you!

**Comment by nwg-piotr** [comment] 2020-04-25 23:08
It seems it really doesn't work as expected on i3. I'm slightly confused, as the command execution returns `success`. This needs a closer look.

**Comment by bolt12** [comment] 2020-04-25 23:42
What do you think is the issue? I can help look into it!

**Comment by nwg-piotr** [comment] 2020-04-26 00:22
Possibly i3 just behaves this way. I'm not sure, as I moved to sway over a year ago, and only use i3 to check my stuff for backwards compatibility. I've recently replaced my laptop with a new one, and my i3 installation may need some more attention to work well.

**Comment by bolt12** [comment] 2020-04-26 10:22
Maybe have an autotiling toggle button?

**Comment by nwg-piotr** [comment] 2020-04-26 12:13
This could be turned off with just `pkill -f autotiling` and back on with `autotiling`, but I'm not sure if this is the way to go.

**Comment by nwg-piotr** [comment] 2020-04-26 12:44
No idea why, but I've just started i3 and switching layouts works as expected together with autotiling. I haven't changed anything.

**Comment by bolt12** [comment] 2020-04-26 12:52
If before I open a new container I say I want the stacked layout it works
but, as soon as I leave the stacked layout I cannot go back to it

**Comment by nwg-piotr** [comment] 2020-04-26 13:01
Hell, I can not reproduce such behaviour... The script applies `spith` or `splitv` only if the current layout is neither floating or stacked or tabbed or fullscreen:

```python
if not is_floating and not is_stacked and not is_tabbed and not is_full_screen:
    new_layout = 'splitv' if con.rect.height > con.rect.width else 'splith'
```

**Comment by ammgws** [comment] 2020-04-26 13:07
Could perhaps check the debug output?

**Comment by nwg-piotr** [comment] 2020-04-26 13:09
Debug out put looks perfectly well here.

**Comment by ammgws** [comment] 2020-04-26 13:24
On @bolt12's system to be sure

**Comment by bolt12** [comment] 2020-04-26 13:26
How to do that?

**Comment by nwg-piotr** [comment] 2020-04-26 13:37
Do not auto-start autotiling. Run it from the terminale instead:

```
autotiling --debug
``` 

Watch messages in the terminal window.

**Comment by bolt12** [comment] 2020-04-26 13:42
The debugging output is fine. I just noticed that my keybings for changing layouts is cmd + w  / cmd + e (the default ones) but when the autotiling is doing its thing cmd + w / cmd + e now change between splith/v...

**Comment by nwg-piotr** [comment] 2020-04-26 13:49
BTW: sorry about not being engaged well enough in this issue. I replaced my old, reliable laptop with a new, AMD-based one. I've been working on it for over a week, but it's still unstable and drives me mad.

**Comment by bolt12** [comment] 2020-04-26 14:08
@nwg-piotr  do not worry at all! Thanks for all the help so far! It is a weird interaction, I just happen to alternate between container layouts pretty often

**Comment by nwg-piotr** [comment] 2020-04-26 15:18
I don't, as long as I'm on dual-headed setup. Thinking about one more external display. :)

**Comment by hisacro** [comment] 2020-04-26 21:46
if you mean this

> press $mod+e for splith/splitv (it toggles), $mod+s for stacking and $mod+w for tabbed.

It's working fine for me..

**Comment by hisacro** [comment] 2020-04-26 21:50
@bolt12 try i3 [debug logs](https://i3wm.org/docs/debugging.html) ..

**Comment by ispanos** [comment] 2020-05-06 22:47
@bolt12 I lost track of what exactly your issue is, but from your original question I think I have a solution. Or I have no idea what you actually need.
>When I enabled autotiling I no longer was able to change the container layout.. is there any way to fix this?
Make sure you have a keybind for `focus parent`. i.e. :
```
bindsym $mod+a focus parent
```
If you want to change the layout, try focusing the parent container before switching layouts with : `layout stacking`, `layout tabbed`, `layout toggle split`.

**Comment by paraduxos** [comment] 2020-05-08 12:30
@ispanos solved the problem. Thanks!

But I think there should be some ways to make `layout <layout>` work as default.

Autotiling disabled: `layout <layout>` auto re-arrange `<stack> <tab> <split>`
![autotiling-disable](https://i.ibb.co/jyrhPMN/autotiling-disable.gif)

Autotiling enabled: `layout <layout>` does not auto re-arrange `<stack> <tab> <split>`
![autotiling-enable](https://i.ibb.co/kc6Rstd/autotiling-enable.gif)

I don't know what is the `ipc` behind auto re-arrange.
Any ideas?

**Comment by ispanos** [comment] 2020-05-08 12:36
> Any ideas?

Give me an exact example of what you want to do please.

**Comment by bolt12** [comment] 2020-05-08 12:39
> @ispanos solved the problem. Thanks!
> 
> But I think there should be some ways to make `layout <layout>` work as default.
> 
> Autotiling disabled: `layout <layout>` auto re-arrange `<stack> <tab> <split>`
> ![autotiling-disable](https://camo.githubusercontent.com/5afc5ff26ac97fc4a5160ebe4c891ab725fe9e7a/68747470733a2f2f692e6962622e636f2f6a797268504d4e2f6175746f74696c696e672d64697361626c652e676966)
> 
> Autotiling enabled: `layout <layout>` does not auto re-arrange `<stack> <tab> <split>`
> ![autotiling-enable](https://camo.githubusercontent.com/01446b2f55ba0e9f7e9a1dce1e124bccb876acb0/68747470733a2f2f692e6962622e636f2f6b6336527374642f6175746f74696c696e672d656e61626c652e676966)
> 
> I don't know what is the `ipc` behind auto re-arrange.
> Any ideas?

Yup this is my problem as well

**Comment by paraduxos** [comment] 2020-05-08 12:40
> > Any ideas?
> 
> Give me an exact example of what you want to do please.

To make `layout <layout>` command work as default (See different between two pictures of enable/disable `autotiling`).

**Comment by ispanos** [comment] 2020-05-08 13:21
> > > Any ideas?
> > 
> > 
> > Give me an exact example of what you want to do please.
> 
> To make `layout <layout>` command work as default (See different between two pictures of enable/disable `autotiling`).

Got it. I understood you question from the beginning. I gave you the answer. 
But you don't want to use `focus parent` after opening a new window? 

When you use `autotiling`, as far as I understand, it uses the `split {h|v}` command, not `layout toggle`.

@nwg-piotr Since I can't test it atm, does it work the same in sway? I don't think it's a real issue to use `focus parent` to change the layout, but it wouldn't deviate from the normal behaviour.

**Comment by mh4nx7net** [comment] 2020-06-27 23:13
![Screenshot from 2020-06-28 06-13-07](https://user-images.githubusercontent.com/33443311/85933918-7dd0ce00-b906-11ea-82ce-97ab02633db2.png)
how i can load this ? 
installation by snap btw

**Comment by nwg-piotr** [comment] 2020-06-28 00:29
I've never ever used snap, and it's not going to change soon. Just install **Manually**, as described in README.

**Comment by morten-b** [comment] 2020-06-28 03:46
I'm away for a few days, but I will have a look when I get back.

-------- Original Message --------

**Comment by ispanos** [comment] 2020-06-28 08:52
> ![Screenshot from 2020-06-28 06-13-07](https://user-images.githubusercontent.com/33443311/85933918-7dd0ce00-b906-11ea-82ce-97ab02633db2.png)
> how i can load this ? 
> installation by snap btw

This is not related to the issue @nwg-piotr can you move or delete the comment?

**Comment by ispanos** [comment] 2020-06-29 17:13
I don't know if there is any real issue here @nwg-piotr .

On i3 without autotilling , say you just hit mod+enter twice and you open 2 terminal windows. Without changing the focus, moving the mouse or pressing any other key.

If you want to open an new window, tabbed with the second terminal, you (**I do it this way**) need to `split v` (`mod+v` for me) and the `layout tabbed` (`mod+t` for me) and then `mod+enter` to get a 3rd terminal, tabbed with the second one. 

When using this script, you can skip over the `split v` step. It's strictly to do with the container focus after creating an new window when the script is running. 

It changes the default behaviour and maybe it could be adjusted to keep the default behaviour, but it doesn't take long to adjust and I don't think this is a bug.

**Comment by nwg-piotr** [comment] 2020-06-29 17:42
> I don't think this is a bug

That's what I said at the very beginning of this thread.

**Comment by ispanos** [comment] 2020-06-29 17:58
@nwg-piotr I had forgotten about that comment. Either `focus parent` after selecting the new layout, so it feels more like the default behaviour, or even better, close this issue.

**Closed** 2020-06-29 18:14 UTC
Labels: question
